UNIPI_SYS_BASE_DIR=/opt/dev/home-auto/code/virtual_pins/
TCP_SERVER_PORT=8080
MODBUS_TCP_ADDR=127.0.0.1
MODBUS_TCP_PORT=5020
MODBUS_RTU_DEVICE=/dev/extcomm/0/0
MODBUS_RTU_BAUD=9600
MODBUS_RTU_PARITY=E
MODBUS_RTU_DATABIT=8
MODBUS_RTU_STOPBIT=1
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_USER=home
POSTGRES_PASSWORD=Albajoan.1234
POSTGRES_DB_NAME=home_auto
